CREATE TABLE MEMBER_STEP(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
	PHONE_NUMBER VARCHAR2(20),
	DELETE_YN CHAR(1),
	CHECK(DELETE_YN IN ('Y', 'N')) DEFAULT 'N'
);
DROP TABLE MEMBER_STEP;
SELECT * FROM MEMBER_STEP;

COMMENT ON COLUMN MEMBER_STEP.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER_STEP.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER_STEP.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER_STEP.PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN MEMBER_STEP.DELETE_YN IS '삭제여부';

CREATE TABLE BOARD_STEP(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER NUMBER,
	CREATE_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER_STEP(MEMBER_NO)
	
);

COMMENT ON COLUMN BOARD_STEP.BOARD_NO IS '글번호';
COMMENT ON COLUMN BOARD_STEP.BOARD_TITLE IS '글제목';
COMMENT ON COLUMN BOARD_STEP.BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN BOARD_STEP.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN BOARD_STEP.CREATE_DATE IS '작성일자';

SELECT BOARD_NO 글번호, BOARD_TITLE 제목, BOARD_CONTENT 내용, BOARD_WRITER 작성자, CREATE_DATE 작성일
FROM BOARD_STEP
ORDER BY BOARD_NO DESC;