-- 01. example 계정을 생성하고 개채생성, 변경, 제거권한과, 
-- DB연결 권한을 추가하고example2 계정을 생성하고 DB연결 권한과 VIEW 생성 권한을 추가한다. 
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER example_kms_seok IDENTIFIED BY "123456";
GRANT CONNECT, RESOURCE TO example_kms_seok;
ALTER USER example_kms_seok DEFAULT TABLESPACE "A230724"
QUOTA 5M ON "A230724";

CREATE USER example2_kms_seok IDENTIFIED BY "123456";
GRANT CONNECT, CREATE VIEW TO example2_kms_seok;

-- 02. example2 계정의 DB연결 권한을 회수 후 계정 삭제한다.
REVOKE CONNECT FROM example2_kms_seok;
DROP USER example2_kms_seok;

-- 03. example계정으로 접속해서 테이블 정의서를 참고하여 MEMBER 테이블과 BOARD 테이블을 생성한다.
CREATE TABLE MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
	PHONE_NUMBER VARCHAR2(20),
	DELETE_YN CHAR(1) DEFAULT 'N',
	CHECK(DELETE_YN IN ('Y', 'N')) 
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN IS '삭제여부';

CREATE TABLE BOARD(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_TITLE VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER NUMBER,
	CREATE_DATE DATE DEFAULT SYSDATE,
	FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER(MEMBER_NO)
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '글번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '글제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '글내용';
COMMENT ON COLUMN BOARD.BOARD_WRITER IS '작성자';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '작성일자';

--04. MEMBER 테이블과 BOARD 테이블에 다음과 같은 데이터를 추가한다.
--단, 회원번호와 글번호는 시퀀스를 생성하여 추가한다.
--시퀀스 :
--SEQ_MEMBER_NO : 100부터 시작하여 100씩 증가
--SEQ_BOARD_NO : 1부터 시작하여 1씩 증가

-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 100;

CREATE SEQUENCE SEQ_BOARD_NO;

-- MEMBER 테이블 데이터 삽입
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step1', 'step11', NULL);
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step2', 'step22','010-1111-2222');
INSERT INTO MEMBER(MEMBER_NO, MEMBER_ID, MEMBER_PASSWORD, PHONE_NUMBER) VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step3', 'step33', NULL);

-- BOARD 테이블 데이터 삽입
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, '첫 글', '스텝평가', 100, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, '두 번째 글', '재밌다', 300, DEFAULT);
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, '세 번째 글', '하하하', 200, DEFAULT);

-- SELECT문 작성
SELECT BOARD_NO 글번호, BOARD_TITLE 제목, BOARD_CONTENT 내용, MEMBER_ID 작성자, TO_CHAR(CREATE_DATE, 'YY/MM/DD') 작성일
FROM BOARD
JOIN MEMBER ON(MEMBER_NO = BOARD_WRITER)
ORDER BY BOARD_NO DESC;

-- 제어 구문
SELECT * FROM MEMBER;
SELECT * FROM BOARD;

DROP TABLE MEMBER;
DROP TABLE BOARD;

DELETE FROM MEMBER;
DELETE FROM BOARD;

DROP SEQUENCE SEQ_MEMBER_NO;
DROP SEQUENCE SEQ_BOARD_NO;

DROP USER example_kms_seok CASCADE;