-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원 번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시글 번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글 번호

-- MEMBER 테이블에 INSERT하기
INSERT INTO MEMBER
VALUES (SEQ_MEMBER_NO.NEXTVAL,
		'firecurry@naver.com',
		'123456',
		'불맛카레', 
		'01094292386',
		'경기도 남양주시 별내동',
		DEFAULT, DEFAULT)
;

SELECT * FROM MEMBER;
DELETE FROM MEMBER WHERE MEMBER_NICKNAME ='물맛카레';

COMMIT;

UPDATE MEMBER 
SET MEMBER_NICKNAME = '5512', 
MEMBER_TEL = '789', 
MEMBER_ADDRESS = '12355'
WHERE MEMBER_EMAIL = 'firecurry@naver.com' 
AND MEMBER_PW = '123456';

-- 로그인
SELECT MEMBER_NO, MEMBER_NICKNAME, MEMBER_TEL, MEMBER_ADDRESS,
	TO_CHAR(ENROLL_DATE, 'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE
FROM MEMBER
WHERE MEMBER_EMAIL = 'firecurry@naver.com'
AND MEMBER_PW = '987654'
AND MEMBER_DEL_FL = 'N';

-- MEMBER 테이블 전체 조회
SELECT * FROM MEMBER 
--ORDER BY MEMBER_NO; -- 오름차순
ORDER BY MEMBER_NO DESC; -- 내림차순

DELETE FROM MEMBER;
COMMIT;

-- 닉네임, 전화번호
UPDATE MEMBER SET MEMBER_NICKNAME = '', MEMBER_TEL = '01099999999'
WHERE MEMBER_NO = 5;

-- 회원 탈퇴
UPDATE MEMBER SET MEMBER_DEL_FL = 'Y'
WHERE MEMBER_NO = 5
AND MEMBER_PW = '123456';

SELECT * FROM BOARD;
SELECT * FROM MEMBER;

-- BOARD 테이블에 INSERT 하기
-- (실행 후 COMMIT/ROLLBACK 무조건 수행)
INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '이름', '내용', DEFAULT, DEFAULT, DEFAULT, '회원번호');

-- 게시글 목록 조회(작성자 닉네임 포함)
-- 1) 삭제되지 않은 글
-- 2) 최신글 순(BOARD_NO 내림차순)
SELECT BOARD_NO, BOARD_TITLE, 
	TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') B_CREATE_DATE,
	READ_COUNT, MEMBER_NO, MEMBER_NICKNAME 
FROM BOARD 
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
ORDER BY BOARD_NO DESC;