-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원 번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시글 번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글 번호

-- MEMBER 테이블에 INSERT하기
INSERT INTO MEMBER
VALUES (SEQ_MEMBER_NO.NEXTVAL,
		'firecurry@naver.com',
		'123456',
		'불맛카레', 
		'01094292386',
		'경기도 남양주시 별내동',
		DEFAULT, DEFAULT)
;

SELECT * FROM MEMBER;
DELETE FROM MEMBER WHERE MEMBER_NICKNAME ='물맛카레';

COMMIT;

UPDATE MEMBER 
SET MEMBER_NICKNAME = '5512', 
MEMBER_TEL = '789', 
MEMBER_ADDRESS = '12355'
WHERE MEMBER_EMAIL = 'firecurry@naver.com' 
AND MEMBER_PW = '123456';